services:
  payment_svc:
    container_name: payment_service
    build:
      context: ./payment_svc
      dockerfile: Dockerfile
    ports:
      - "9041:${PAYMENT_HTTP_SERVER_PORT}"
    env_file:
      - .env
      - ./payment_svc/.env
    networks:
      - booking_network

networks:
  booking_network:
    driver: bridge
    name: booking_network

volumes:
  payment_service_data:

