services:
  zookeeper:
    hostname: zookeeper
    image: bitnami/zookeeper:latest
    restart: always
    expose:
    - "2181"
    ports:
    - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
      ALLOW_PLAINTEXT_LISTENER: yes
  
  kafka:
    hostname: kafka
    image: bitnami/kafka:2.7.0
    restart: always
    env_file:
    - notification_svc/pkg/kafka/kafka-variables.env
    depends_on:
    - zookeeper
    expose:
    - "9092"
    - "8082"
    - "8083"
    ports:
    - '9092:9092'
    - '8082:8082'
    - '8083:8083'
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes

  notification_svc:
    container_name: notification_svc
    build: 
      context: notification_svc
    environment:
      - kafkaURL=kafka:9092
      - topic=notification_svc
    depends_on:
      - kafka
    restart: always