/*
Payment Webhook API

API для обработки платежей по комнатам.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the HandlePayment500Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HandlePayment500Response{}

// HandlePayment500Response struct for HandlePayment500Response
type HandlePayment500Response struct {
	Error *string `json:"error,omitempty"`
}

// NewHandlePayment500Response instantiates a new HandlePayment500Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHandlePayment500Response() *HandlePayment500Response {
	this := HandlePayment500Response{}
	return &this
}

// NewHandlePayment500ResponseWithDefaults instantiates a new HandlePayment500Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHandlePayment500ResponseWithDefaults() *HandlePayment500Response {
	this := HandlePayment500Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *HandlePayment500Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlePayment500Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *HandlePayment500Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *HandlePayment500Response) SetError(v string) {
	o.Error = &v
}

func (o HandlePayment500Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HandlePayment500Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableHandlePayment500Response struct {
	value *HandlePayment500Response
	isSet bool
}

func (v NullableHandlePayment500Response) Get() *HandlePayment500Response {
	return v.value
}

func (v *NullableHandlePayment500Response) Set(val *HandlePayment500Response) {
	v.value = val
	v.isSet = true
}

func (v NullableHandlePayment500Response) IsSet() bool {
	return v.isSet
}

func (v *NullableHandlePayment500Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHandlePayment500Response(val *HandlePayment500Response) *NullableHandlePayment500Response {
	return &NullableHandlePayment500Response{value: val, isSet: true}
}

func (v NullableHandlePayment500Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHandlePayment500Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


