/*
Payment Webhook API

API для обработки платежей по комнатам.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the HandlePayment200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HandlePayment200Response{}

// HandlePayment200Response struct for HandlePayment200Response
type HandlePayment200Response struct {
	Message *string `json:"message,omitempty"`
}

// NewHandlePayment200Response instantiates a new HandlePayment200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHandlePayment200Response() *HandlePayment200Response {
	this := HandlePayment200Response{}
	return &this
}

// NewHandlePayment200ResponseWithDefaults instantiates a new HandlePayment200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHandlePayment200ResponseWithDefaults() *HandlePayment200Response {
	this := HandlePayment200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *HandlePayment200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlePayment200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *HandlePayment200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *HandlePayment200Response) SetMessage(v string) {
	o.Message = &v
}

func (o HandlePayment200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HandlePayment200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableHandlePayment200Response struct {
	value *HandlePayment200Response
	isSet bool
}

func (v NullableHandlePayment200Response) Get() *HandlePayment200Response {
	return v.value
}

func (v *NullableHandlePayment200Response) Set(val *HandlePayment200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableHandlePayment200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableHandlePayment200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHandlePayment200Response(val *HandlePayment200Response) *NullableHandlePayment200Response {
	return &NullableHandlePayment200Response{value: val, isSet: true}
}

func (v NullableHandlePayment200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHandlePayment200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


