// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payment Webhook API
 *
 * API для обработки платежей по комнатам.
 *
 * API version: 1.0.0
 */

package openapi




type HandlePayment500Response struct {

	Error string `json:"error,omitempty"`
}

// AssertHandlePayment500ResponseRequired checks if the required fields are not zero-ed
func AssertHandlePayment500ResponseRequired(obj HandlePayment500Response) error {
	return nil
}

// AssertHandlePayment500ResponseConstraints checks if the values respects the defined constraints
func AssertHandlePayment500ResponseConstraints(obj HandlePayment500Response) error {
	return nil
}
