// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payment System API
 *
 * API для обработки платежей за комнаты.
 *
 * API version: 1.0.0
 */

package openapi

type CreatePaymentPostRequest struct {

	// ID комнаты
	RoomId string `json:"room_id,omitempty"`

	// Сумма платежа
	Amount float32 `json:"amount,omitempty"`

	// URL для получения уведомлений о статусе платежа
	WebhookUrl string `json:"webhook_url,omitempty"`
}

// AssertCreatePaymentPostRequestRequired checks if the required fields are not zero-ed
func AssertCreatePaymentPostRequestRequired(obj CreatePaymentPostRequest) error {
	return nil
}

// AssertCreatePaymentPostRequestConstraints checks if the values respects the defined constraints
func AssertCreatePaymentPostRequestConstraints(obj CreatePaymentPostRequest) error {
	return nil
}
