/*
Payment System API

API для обработки платежей за комнаты.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreatePaymentPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePaymentPostRequest{}

// CreatePaymentPostRequest struct for CreatePaymentPostRequest
type CreatePaymentPostRequest struct {
	// ID комнаты
	RoomId *string `json:"room_id,omitempty"`
	// Сумма платежа
	Amount *float32 `json:"amount,omitempty"`
	// URL для получения уведомлений о статусе платежа
	WebhookUrl *string `json:"webhook_url,omitempty"`
}

// NewCreatePaymentPostRequest instantiates a new CreatePaymentPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePaymentPostRequest() *CreatePaymentPostRequest {
	this := CreatePaymentPostRequest{}
	return &this
}

// NewCreatePaymentPostRequestWithDefaults instantiates a new CreatePaymentPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePaymentPostRequestWithDefaults() *CreatePaymentPostRequest {
	this := CreatePaymentPostRequest{}
	return &this
}

// GetRoomId returns the RoomId field value if set, zero value otherwise.
func (o *CreatePaymentPostRequest) GetRoomId() string {
	if o == nil || IsNil(o.RoomId) {
		var ret string
		return ret
	}
	return *o.RoomId
}

// GetRoomIdOk returns a tuple with the RoomId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePaymentPostRequest) GetRoomIdOk() (*string, bool) {
	if o == nil || IsNil(o.RoomId) {
		return nil, false
	}
	return o.RoomId, true
}

// HasRoomId returns a boolean if a field has been set.
func (o *CreatePaymentPostRequest) HasRoomId() bool {
	if o != nil && !IsNil(o.RoomId) {
		return true
	}

	return false
}

// SetRoomId gets a reference to the given string and assigns it to the RoomId field.
func (o *CreatePaymentPostRequest) SetRoomId(v string) {
	o.RoomId = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *CreatePaymentPostRequest) GetAmount() float32 {
	if o == nil || IsNil(o.Amount) {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePaymentPostRequest) GetAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *CreatePaymentPostRequest) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *CreatePaymentPostRequest) SetAmount(v float32) {
	o.Amount = &v
}

// GetWebhookUrl returns the WebhookUrl field value if set, zero value otherwise.
func (o *CreatePaymentPostRequest) GetWebhookUrl() string {
	if o == nil || IsNil(o.WebhookUrl) {
		var ret string
		return ret
	}
	return *o.WebhookUrl
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePaymentPostRequest) GetWebhookUrlOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookUrl) {
		return nil, false
	}
	return o.WebhookUrl, true
}

// HasWebhookUrl returns a boolean if a field has been set.
func (o *CreatePaymentPostRequest) HasWebhookUrl() bool {
	if o != nil && !IsNil(o.WebhookUrl) {
		return true
	}

	return false
}

// SetWebhookUrl gets a reference to the given string and assigns it to the WebhookUrl field.
func (o *CreatePaymentPostRequest) SetWebhookUrl(v string) {
	o.WebhookUrl = &v
}

func (o CreatePaymentPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePaymentPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RoomId) {
		toSerialize["room_id"] = o.RoomId
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.WebhookUrl) {
		toSerialize["webhook_url"] = o.WebhookUrl
	}
	return toSerialize, nil
}

type NullableCreatePaymentPostRequest struct {
	value *CreatePaymentPostRequest
	isSet bool
}

func (v NullableCreatePaymentPostRequest) Get() *CreatePaymentPostRequest {
	return v.value
}

func (v *NullableCreatePaymentPostRequest) Set(val *CreatePaymentPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePaymentPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePaymentPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePaymentPostRequest(val *CreatePaymentPostRequest) *NullableCreatePaymentPostRequest {
	return &NullableCreatePaymentPostRequest{value: val, isSet: true}
}

func (v NullableCreatePaymentPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePaymentPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
