// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Hotel Booking API
 *
 * API для управления бронированием отелей
 *
 * API version: 1.0.0
 */

package openapi




type ApprovePaymentWebhookRequest struct {

	// ID комнаты
	RoomId string `json:"room_id"`

	// Подтверждение платежа
	Approve bool `json:"approve"`
}

// AssertApprovePaymentWebhookRequestRequired checks if the required fields are not zero-ed
func AssertApprovePaymentWebhookRequestRequired(obj ApprovePaymentWebhookRequest) error {
	elements := map[string]interface{}{
		"room_id": obj.RoomId,
		"approve": obj.Approve,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertApprovePaymentWebhookRequestConstraints checks if the values respects the defined constraints
func AssertApprovePaymentWebhookRequestConstraints(obj ApprovePaymentWebhookRequest) error {
	return nil
}
