// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Hotel Booking API
 *
 * API для управления бронированием отелей
 *
 * API version: 1.0.0
 */

package openapi


import (
	"time"
)



type BookedRoom struct {

	// ID забронированной комнаты
	ID string `json:"ID"`

	// ID отеля
	HotelID string `json:"HotelID"`

	// Дата заезда
	Entry time.Time `json:"Entry"`

	// Дата выезда
	Exit time.Time `json:"Exit"`

	// Email пользователя, забронировавшего комнату
	Email string `json:"Email"`

	// оплачена ли комната
	IsPaid bool `json:"IsPaid"`
}

// AssertBookedRoomRequired checks if the required fields are not zero-ed
func AssertBookedRoomRequired(obj BookedRoom) error {
	elements := map[string]interface{}{
		"ID": obj.ID,
		"HotelID": obj.HotelID,
		"Entry": obj.Entry,
		"Exit": obj.Exit,
		"Email": obj.Email,
		"IsPaid": obj.IsPaid,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertBookedRoomConstraints checks if the values respects the defined constraints
func AssertBookedRoomConstraints(obj BookedRoom) error {
	return nil
}
