// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Hotel Booking API
 *
 * API для управления бронированием отелей
 *
 * API version: 1.0.0
 */

package openapi




type Room struct {

	// ID комнаты
	ID string `json:"ID"`

	// ID отеля
	HotelID string `json:"HotelID"`

	// Название комнаты
	Name string `json:"Name"`

	// Описание комнаты
	Description string `json:"Description,omitempty"`

	// Цена за комнату
	Price int32 `json:"Price"`
}

// AssertRoomRequired checks if the required fields are not zero-ed
func AssertRoomRequired(obj Room) error {
	elements := map[string]interface{}{
		"ID": obj.ID,
		"HotelID": obj.HotelID,
		"Name": obj.Name,
		"Price": obj.Price,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRoomConstraints checks if the values respects the defined constraints
func AssertRoomConstraints(obj Room) error {
	return nil
}
