// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Hotel Booking API
 *
 * API для управления бронированием отелей
 *
 * API version: 1.0.0
 */

package openapi




type ApprovePaymentWebhook200Response struct {

	Message string `json:"message,omitempty"`
}

// AssertApprovePaymentWebhook200ResponseRequired checks if the required fields are not zero-ed
func AssertApprovePaymentWebhook200ResponseRequired(obj ApprovePaymentWebhook200Response) error {
	return nil
}

// AssertApprovePaymentWebhook200ResponseConstraints checks if the values respects the defined constraints
func AssertApprovePaymentWebhook200ResponseConstraints(obj ApprovePaymentWebhook200Response) error {
	return nil
}
