openapi: 3.0.3
info:
  description: API для управления бронированием отелей
  title: Hotel Booking API
  version: 1.0.0
servers:
- url: /
paths:
  /unbooked-rooms/{hotel_id}:
    get:
      operationId: getUnbookedRooms
      parameters:
      - description: ID отеля
        explode: false
        in: path
        name: hotel_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Room'
                type: array
          description: Список свободных комнат
        "404":
          description: Отель или комнаты не найдены
        "500":
          description: Внутренняя ошибка сервера
      summary: Получить список свободных комнат по ID отеля
  /booked-rooms/{hotel_id}:
    get:
      operationId: getBookedRooms
      parameters:
      - description: ID отеля
        explode: false
        in: path
        name: hotel_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BookedRoom'
                type: array
          description: Список забронированных комнат
        "404":
          description: Отель или забронированные комнаты не найдены
        "500":
          description: Внутренняя ошибка сервера
      summary: Получить список забронированных комнат по ID отеля
components:
  schemas:
    Room:
      example:
        HotelID: HotelID
        Description: Description
        Price: 0
        ID: ID
        Name: Name
      properties:
        ID:
          description: ID комнаты
          type: string
        HotelID:
          description: ID отеля
          type: string
        Name:
          description: Название комнаты
          type: string
        Description:
          description: Описание комнаты
          type: string
        Price:
          description: Цена за комнату
          format: int32
          type: integer
      required:
      - HotelID
      - ID
      - Name
      - Price
      type: object
    BookedRoom:
      example:
        Entry: 2000-01-23T04:56:07.000+00:00
        HotelID: HotelID
        Email: Email
        ID: ID
        Exit: 2000-01-23T04:56:07.000+00:00
      properties:
        ID:
          description: ID забронированной комнаты
          type: string
        HotelID:
          description: ID отеля
          type: string
        Entry:
          description: Дата заезда
          format: date-time
          type: string
        Exit:
          description: Дата выезда
          format: date-time
          type: string
        Email:
          description: "Email пользователя, забронировавшего комнату"
          format: email
          type: string
      required:
      - Email
      - Entry
      - Exit
      - HotelID
      - ID
      type: object
