// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payment Webhook API
 *
 * API для обработки платежей по комнатам.
 *
 * API version: 1.0.0
 */

package openapi




type HandlePayment200Response struct {

	Message string `json:"message,omitempty"`
}

// AssertHandlePayment200ResponseRequired checks if the required fields are not zero-ed
func AssertHandlePayment200ResponseRequired(obj HandlePayment200Response) error {
	return nil
}

// AssertHandlePayment200ResponseConstraints checks if the values respects the defined constraints
func AssertHandlePayment200ResponseConstraints(obj HandlePayment200Response) error {
	return nil
}
