// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payment Webhook API
 *
 * API для обработки платежей по комнатам.
 *
 * API version: 1.0.0
 */

package openapi




type Payment struct {

	// Сумма платежа
	Price float32 `json:"price"`

	// Идентификатор комнаты
	RoomId string `json:"room_id"`
}

// AssertPaymentRequired checks if the required fields are not zero-ed
func AssertPaymentRequired(obj Payment) error {
	elements := map[string]interface{}{
		"price": obj.Price,
		"room_id": obj.RoomId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPaymentConstraints checks if the values respects the defined constraints
func AssertPaymentConstraints(obj Payment) error {
	return nil
}
