// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payment Webhook API
 *
 * API для обработки платежей по комнатам.
 *
 * API version: 1.0.0
 */

package openapi




type HandlePayment400Response struct {

	Error string `json:"error,omitempty"`
}

// AssertHandlePayment400ResponseRequired checks if the required fields are not zero-ed
func AssertHandlePayment400ResponseRequired(obj HandlePayment400Response) error {
	return nil
}

// AssertHandlePayment400ResponseConstraints checks if the values respects the defined constraints
func AssertHandlePayment400ResponseConstraints(obj HandlePayment400Response) error {
	return nil
}
